### ISSUE TITLE
Adding via SwiftPM?

### ISSUE THREAD

**Issue by JimWallace** [awxkee/zstd.swift#1]
I can add this dependency to an and Xcode project, either Swift UI or CLI, and it compiles. I have not been able to add it as a dependency to a package. i.e., using: 

.package(url: "https://github.com/awxkee/zstd.swift.git", from: "1.0.1"),

and Adding "zstd" as a Dependency to my target. Should the package work for this? Having a hard time understanding why it's not finding "zstd" as a product.

**Comment by awxkee** [comment]
Have you tried `  .product(name: "zstd", package: "zstd.swift"),`?

**Comment by JimWallace** [comment]
That was it, thanks for the speedy response to a simple question.
